/*
2022년 1월, 저자 별, 카테고리 별 매출액 구하기 
저자 id, 저자명, 카테고리, 매출액=판매량*판매가 출력
저자id 기준 오릋마, 카테고리 내림차
*/
SELECT  A.AUTHOR_ID, A.AUTHOR_NAME,B.CATEGORY, SUM(S.SALES*B.PRICE) AS SALES
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE >= '2022-01-01' AND S.SALES_DATE <'2022-02-01'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID , B.CATEGORY DESC
