/*
음식 종류별로 즐겨찾기수가 많은 식당의
종류, 아이디, 이름 즐찾수
종류 기준 내림차순
*/
SELECT I.FOOD_TYPE, I.REST_ID,I.REST_NAME, I.FAVORITES
FROM REST_INFO I
JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS F FROM REST_INFO
      GROUP BY FOOD_TYPE
     ) M
ON I.FOOD_TYPE = M.FOOD_TYPE
AND I.FAVORITES = M.F
ORDER BY I.FOOD_TYPE DESC
