/*
크기 기준 내림차순 정렬시 상위 25퍼가지 크리티컬, 50퍼, 75퍼, 100퍼
4개로 쪼개서 출력
*/

SELECT ID,
CASE
WHEN PER =1 THEN 'CRITICAL'
WHEN PER =2 THEN 'HIGH'
WHEN PER =3 THEN 'MEDIUM'
ELSE 'LOW'
END AS COLONY_NAME
FROM (SELECT ID, NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) AS PER
      FROM ECOLI_DATA) AS E
ORDER BY ID