/*
년,월, 성별 별로 상품 구매 회원수 집계
년,월, 성별 기준 오름차순
단 성별 정보가 없으면 결과에서 제외
DISTINCT를 이용해 동일 회원의 중복 집계 제외
*/
SELECT YEAR(S.SALES_DATE) AS YEAR
,MONTH(S.SALES_DATE) AS  MONTH
,I.GENDER
,COUNT(DISTINCT I.USER_ID) AS USERS
FROM USER_INFO I
JOIN ONLINE_SALE S
ON I.USER_ID = S.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY YEAR(S.SALES_DATE),MONTH(S.SALES_DATE),I.GENDER
ORDER BY YEAR,MONTH, I.GENDER
 