/*
종류별 이름과, 잡은 수 출력, 컬럼명 변경, 잡은 수 기준 내림차
*/

SELECT COUNT(*) AS FISH_COUNT,N.FISH_NAME AS FISH_NAME 
FROM FISH_INFO I
JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
GROUP BY N.FISH_NAME
ORDER BY FISH_COUNT DESC