-- 코드를 작성해주세요
/*
100 이하 low, 100 ~ 1000 medium, 1000 초과 high
id와 분류 출력
*/
SELECT ID,
CASE 
    WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
    WHEN SIZE_OF_COLONY <= 1000 THEN 'MEDIUM'
    ELSE 'HIGH'
END AS SIZE
FROM ECOLI_DATA
ORDER BY ID