/*
부모 형질을 모두 보유해야 함
id 형질 부모 형질 출력
*/
SELECT C.ID, C.GENOTYPE , P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA C
JOIN ECOLI_DATA P
ON C.PARENT_ID  = P.ID
WHERE (C.GENOTYPE & P.GENOTYPE)  = P.GENOTYPE
ORDER BY C.ID