/*
분화 연도, 분화 연도별 대장균 크기 편차, id
편차 = 분화 연도별 가장 큰 대장균 크기 - 각 대장균 크기
연도에 대해 오름차순 , 편차에 오름차

연도별 크기가 가장 큰 테이블 만든 후 편차 제공
*/
SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, M.MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV, E.ID
FROM ECOLI_DATA E
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS Y , MAX(SIZE_OF_COLONY) AS MAX_SIZE
FROM ECOLI_DATA A
GROUP BY YEAR(DIFFERENTIATION_DATE)
      ) M
ON M.Y = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV