/*
부서별 id, 영문명, 평균 연봉 조회
*/
SELECT H.DEPT_ID, H.DEPT_NAME_EN, T.SAL AS AVG_SAL
FROM HR_DEPARTMENT H
JOIN (SELECT D.DEPT_ID, ROUND(AVG(E.SAL),0) AS SAL
     FROM HR_DEPARTMENT D
      JOIN HR_EMPLOYEES E
      ON D.DEPT_ID = E.DEPT_ID
      GROUP BY D.DEPT_ID
     ) T
ON H.DEPT_ID = T.DEPT_ID
ORDER BY AVG_SAL DESC