/*
2022.01 카테고리 별 도서 판매량 합산
카테고리 , 총 판매량 출력
고리명 기준 오름차
*/
SELECT  B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE >= '2022-01-01' 
AND S.SALES_DATE < '2022-02-01' 
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY